/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef MAINBOARD_FOXCONN_G31MX_STOCK_PREINIT_H
#define MAINBOARD_FOXCONN_G31MX_STOCK_PREINIT_H

void g31mx_stock_preinit(void);

#endif /* MAINBOARD_FOXCONN_G31MX_STOCK_PREINIT_H */
